/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AssistantRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Schedule.DailySchedule;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keert
 */
public class AssistantWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;

    /**
     * Creates new form AssistantWorkAreaJPanel
     */
    public AssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        try {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.account = account;
            this.enterprise = enterprise;
            System.out.println("Displaying the enterpirse type");
            String entValue = enterprise.getName();
            if (entValue.trim().length() > 0 && entValue != null) {
                valueLabel.setText(enterprise.getName());
            } else {
                valueLabel.setVisible(false);
            }
            addNewDay();
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Oops! we don't want you to see this. Please allow us sometime to fix it");
        }
    }
    
    private void addNewDay() {
        try {
            System.out.println("setting the calendar");
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            Calendar c = Calendar.getInstance();
            for (int i = 0; i < 30; i++) {
                Date today = new Date();
                c.setTime(today);
                c.add(Calendar.DAY_OF_MONTH, i);
                Date date = c.getTime();
                for (Employee lawyer : account.getEmployee().getLawyerDirectory().getEmployeeList()) {
                    boolean existing = false;
                    for (DailySchedule ds : lawyer.getSchedule().getDailyScheduleList()) {
                        if (ds.toString().equals(fmt.format(date))) {
                            existing = true;
                            break;
                        }
                    }
                    if (!existing) {
                        lawyer.getSchedule().createDailySchedule(date);
                    }
                }
            }
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Oops! we don't want you to see this. Please allow us sometime to fix it");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        manageScheduleJButton = new javax.swing.JButton();
        manageRequestJButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        manageScheduleJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageScheduleJButton.setText("Manage Lawyer Schedules");
        manageScheduleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageScheduleJButtonActionPerformed(evt);
            }
        });

        manageRequestJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageRequestJButton.setText("Manage Schedule Requests");
        manageRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestJButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Stencil", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Assistant work area");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageScheduleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageScheduleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageScheduleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageScheduleJButtonActionPerformed
        try {
            System.out.println("directing to manage schedule screen");
            ManageSchedulesJPanel msjp = new ManageSchedulesJPanel(userProcessContainer, account);
            userProcessContainer.add("ManageSchedulesJPanel", msjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Oops! we don't want you to see this. Please allow us sometime to fix it");
        }
    }//GEN-LAST:event_manageScheduleJButtonActionPerformed

    private void manageRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestJButtonActionPerformed
        try {
            System.out.println("directing to manage requests screen");
            ManageRequestJPanel mrjp = new ManageRequestJPanel(userProcessContainer, account);
            userProcessContainer.add("ManageRequestJPanel", mrjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Oops! we don't want you to see this. Please allow us sometime to fix it");
        }
    }//GEN-LAST:event_manageRequestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton manageRequestJButton;
    private javax.swing.JButton manageScheduleJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
